using Microsoft.Extensions.Logging;
using SessionFinder.Core.Results;
using SessionFinder.Presentation.Abstractions;

namespace SessionFinder.Presentation.Shell;

/// <summary>
/// The one seam every user-initiated command runs through: it turns a refusal into something the
/// user can read, an unexpected exception into a log entry plus a notification, and a cancellation
/// into nothing at all.
/// </summary>
/// <remarks>
/// <para>
/// This is the desktop equivalent of the exception middleware a web application puts in front of
/// its handlers. The reason it is one type rather than a <c>try</c> in each command is the same
/// reason the middleware is one type: the moment there are six of them, one of them is wrong, and
/// the one that is wrong is the one that fails silently.
/// </para>
/// <para>
/// A cancellation is not a failure and is not reported anywhere. It is what pressing Escape, or
/// closing the window over a running action, produces, and a notification saying so would be noise
/// generated by the user's own dismissal.
/// </para>
/// </remarks>
/// <param name="notifier">How a refusal or a failure reaches the user.</param>
/// <param name="logger">Where the detail of a failure is recorded.</param>
public sealed class AppCommandGuard(IUserNotifier notifier, ILogger<AppCommandGuard> logger)
{
    private const string UnexpectedFailureMessage = "Something went wrong. The log has the detail.";

    /// <summary>
    /// Runs work that reports an expected refusal as a result.
    /// </summary>
    /// <param name="action">What the user asked for, for the log. Never a value they typed.</param>
    /// <param name="failureTitle">The heading shown if it does not work.</param>
    /// <param name="work">The work to run.</param>
    /// <returns><see langword="true"/> when the work completed and was not refused.</returns>
    public async Task<bool> RunAsync(string action, string failureTitle, Func<Task<Result>> work)
    {
        ArgumentNullException.ThrowIfNull(work);

        try
        {
            var result = await work().ConfigureAwait(true);

            return Report(action, failureTitle, result);
        }
        catch (OperationCanceledException)
        {
            return false;
        }
        catch (Exception exception)
        {
            ReportUnexpected(action, failureTitle, exception);

            return false;
        }
    }

    /// <summary>
    /// Runs work whose only failure mode is an exception.
    /// </summary>
    /// <param name="action">What the user asked for, for the log. Never a value they typed.</param>
    /// <param name="failureTitle">The heading shown if it does not work.</param>
    /// <param name="work">The work to run.</param>
    /// <returns><see langword="true"/> when the work completed.</returns>
    public Task<bool> RunAsync(string action, string failureTitle, Func<Task> work)
    {
        ArgumentNullException.ThrowIfNull(work);

        return RunAsync(action, failureTitle, async () =>
        {
            await work().ConfigureAwait(true);

            return Result.Success();
        });
    }

    private bool Report(string action, string failureTitle, Result result)
    {
        if (result.Error is not { } error)
        {
            return true;
        }

        AppCommandGuardLog.CommandRefused(logger, action, error.Code);
        notifier.Notify(UserNotification.Warning(failureTitle, error.Message));

        return false;
    }

    private void ReportUnexpected(string action, string failureTitle, Exception exception)
    {
        AppCommandGuardLog.CommandThrew(logger, action, exception);
        notifier.Notify(UserNotification.Error(failureTitle, UnexpectedFailureMessage));
    }
}
