using SessionFinder.Core.Features.DailyRecap;

namespace SessionFinder.Core.Tests.Features.DailyRecap;

public sealed class PromptTextTests
{
    [Fact]
    public void Clean_APromptBehindAnEditorSelectionNotice_KeepsOnlyWhatWasTyped()
    {
        const string raw =
            "<ide_selection>The user selected the lines 84 to 84 from /work/app.py\nx = 1</ide_selection>\nwhy is this zero?";

        PromptText.Clean(raw).Should().Be("why is this zero?");
    }

    [Theory]
    [InlineData("<command-name>/plan</command-name>\n<command-message>plan</command-message>")]
    [InlineData("<local-command-stdout>Set model to opus</local-command-stdout>")]
    [InlineData("<task-notification> <task-id>b1</task-id> done </task-notification>")]
    [InlineData("[Request interrupted by user]")]
    [InlineData("[Request interrupted by user for tool use]")]
    [InlineData("Caveat: The messages below were generated by the user while running local commands.")]
    [InlineData("   \n\t ")]
    public void Clean_SomethingTheHarnessWrote_IsNotAPrompt(string raw)
    {
        PromptText.Clean(raw).Should().BeNull();
    }

    [Fact]
    public void Clean_PastedContent_IsRemovedAndTheQuestionAroundItKept()
    {
        const string raw = "i get this <pasted_content id=\"1\">error: boom\nat line 3</pasted_content> what is wrong?";

        PromptText.Clean(raw).Should().Be("i get this what is wrong?");
    }

    [Fact]
    public void Clean_ALessThanSignInOrdinaryText_IsLeftAlone()
    {
        PromptText.Clean("is a < b always true here?").Should().Be("is a < b always true here?");
    }

    [Fact]
    public void Clean_AMultiLinePrompt_IsFlattenedToOneLine()
    {
        PromptText.Clean("first line\n\n   second line").Should().Be("first line second line");
    }

    [Fact]
    public void Truncate_LongText_EndsOnAWordAndAnEllipsis()
    {
        PromptText.Truncate("one two three four five six", 16).Should().Be("one two three…");
    }

    [Fact]
    public void Truncate_ShortText_IsUnchanged()
    {
        PromptText.Truncate("short", 16).Should().Be("short");
    }
}
